<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
      
      <!-- Fixed local duplicate AssemblyInfo attributes conflict on macOS -->
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>


      <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>